#!/usr/bin/env bash

# Check if all four required parameters are provided
if [ $# -ne 4 ]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

# Assign parameters to variables
FILE_PATH="$1"
SERVER_IP="$2"
USERNAME="$3"
SSH_KEY="$4"

# Use scp to transfer the file to the user's home directory on the server
# -o StrictHostKeyChecking=no disables strict host key checking
scp -o StrictHostKeyChecking=no -i "$SSH_KEY" "$FILE_PATH" "$USERNAME@$SERVER_IP:~/"

# Check the exit status of scp
if [ $? -eq 0 ]; then
  echo "File successfully transferred to $USERNAME@$SERVER_IP:~/"
else
  echo "File transfer failed."
fi

